export interface TemplateFurniture {
  type: string;
  name: string;
  x: number;
  y: number;
  width: number;
  length: number;
  color: string;
  rotation?: number;
}

export interface RoomTemplate {
  id: string;
  name: string;
  icon: string;
  dimensions: { width: number; length: number };
  defaultFurniture: TemplateFurniture[];
  suggestedWallColor: string;
  suggestedFloorColor: string;
  suggestedFloorType: string;
}

export const roomTemplates: RoomTemplate[] = [
  {
    id: "living-room",
    name: "Living Room",
    icon: "🛋️",
    dimensions: { width: 22, length: 18 },

    defaultFurniture: [
      {
        type: "two-seater-sofa",
        name: "2 Seater Sofa",
        x: 7.5,
        y: 0.5,
        width: 7,
        length: 3,
        color: "#f3d9c4",
      },
      {
        type: "coffee-table",
        name: "Coffee Table",
        x: 9,
        y: 5.5,
        width: 4,
        length: 2,
        color: "#4682B4",
      },
      {
        type: "arm-chair",
        name: "Arm Chair",
        x: 15.5,
        y: 5,
        width: 2.5,
        length: 2.5,
        color: "#228B22",
        rotation: 90,
      },
      {
        type: "arm-chair",
        name: "Arm Chair",
        x: 4,
        y: 5,
        width: 2.5,
        length: 2.5,
        color: "#228B22",
        rotation: 270,
      },
      {
        type: "books-helf",
        name: "Bookshelf",
        x: -0.5,
        y: 12,
        width: 2.5,
        length: 0.8,
        color: "#8B4513",
        rotation: 90,
      },
      {
        type: "tv-stand",
        name: "TV Stand",
        x: 8,
        y: 16,
        width: 6,
        length: 1.5,
        color: "#e69141",
        rotation: 180,
      },
    ],

    suggestedWallColor: "#F5F0EB",
    suggestedFloorColor: "#d4a76a",
    suggestedFloorType: "tile",
  },

  {
    id: "bedroom",
    name: "Bedroom",
    icon: "🛏️",
    dimensions: { width: 18, length: 16 },

    defaultFurniture: [
      {
        type: "king-bed",
        name: "King Bed",
        x: 6,
        y: 0.5,
        width: 6,
        length: 6,
        color: "#C8D4DE",
      },
      {
        type: "night-stand",
        name: "Nightstand Left",
        x: 4,
        y: 0.5,
        width: 1.8,
        length: 1.8,
        color: "#8B4513",
      },
      {
        type: "night-stand",
        name: "Nightstand Right",
        x: 12.2,
        y: 0.5,
        width: 1.8,
        length: 1.8,
        color: "#8B4513",
      },
      {
        type: "wardrobe-01",
        name: "Wardrobe",
        x: 14.3,
        y: 10,
        width: 5,
        length: 2,
        color: "#c6c2be",
        rotation: 90,
      },
      {
        type: "dresser-01",
        name: "Dresser",
        x: 14.9,
        y: 5,
        width: 4,
        length: 1.8,
        color: "#8B4513",
        rotation: 90,
      },
      {
        type: "tv-stand",
        name: "TV Stand",
        x: 6,
        y: 14.2,
        width: 6,
        length: 1.5,
        color: "#e69141",
        rotation: 180,
      },
      {
        type: "arm-chair",
        name: "Arm Chair",
        x: 0.5,
        y: 3,
        width: 2.5,
        length: 2.5,
        color: "#228B22",
        rotation: 330,
      },
    ],

    suggestedWallColor: "#F5E6D3",
    suggestedFloorColor: "#d4a76a",
    suggestedFloorType: "wood",
  },

  {
    id: "home-office",
    name: "Home Office",
    icon: "💻",
    dimensions: { width: 12, length: 14 },

    defaultFurniture: [
      {
        type: "office-desk",
        name: "Office Desk",
        x: 0.5,
        y: 3.5,
        width: 5,
        length: 2.5,
        color: "#2F4F4F",
      },
      {
        type: "computer-chair",
        name: "Computer Chair",
        x: 2,
        y: 1.5,
        width: 2,
        length: 2,
        color: "#333333",
      },
      {
        type: "books-helf",
        name: "Bookshelf",
        x: 8.5,
        y: 0.3,
        width: 3,
        length: 1,
        color: "#8B4513",
        rotation: 360,
      },
      {
        type: "two-seater-sofa",
        name: "2 Seater Sofa",
        x: 6.8,
        y: 8.8,
        width: 7,
        length: 3,
        color: "#f3d9c4",
        rotation: 90,
      },
      {
        type: "coffee-table",
        name: "Coffee Table",
        x: 5,
        y: 9.4,
        width: 4,
        length: 2,
        color: "#4682B4",
        rotation: 90,
      },
    ],

    suggestedWallColor: "#E8E4E0",
    suggestedFloorColor: "#b0abad",
    suggestedFloorType: "carpet",
  },

  {
    id: "dining-room",
    name: "Dining Room",
    icon: "🍽️",
    dimensions: { width: 16, length: 14 },

    defaultFurniture: [
      {
        type: "dining-table",
        name: "Dining Table (6 Seat)",
        x: 5,
        y: 5,
        width: 6,
        length: 4,
        color: "#dbd7d7",
      },
      {
        type: "single-chair",
        name: "Single Chair",
        x: 4,
        y: 6.3,
        width: 1.5,
        length: 1.5,
        color: "#4682B4",
        rotation: 270,
      },
      {
        type: "single-chair",
        name: "Single Chair",
        x: 10.5,
        y: 6.3,
        width: 1.5,
        length: 1.5,
        color: "#4682B4",
        rotation: 90,
      },
      {
        type: "single-chair",
        name: "Single Chair",
        x: 6,
        y: 4,
        width: 1.5,
        length: 1.5,
        color: "#4682B4",
      },
      {
        type: "single-chair",
        name: "Single Chair",
        x: 8.5,
        y: 8.5,
        width: 1.5,
        length: 1.5,
        color: "#4682B4",
        rotation: 180,
      },
      {
        type: "single-chair",
        name: "Single Chair",
        x: 6,
        y: 8.5,
        width: 1.5,
        length: 1.5,
        color: "#4682B4",
        rotation: 180,
      },
      {
        type: "single-chair",
        name: "Single Chair",
        x: 8.5,
        y: 4,
        width: 1.5,
        length: 1.5,
        color: "#4682B4",
      },
    ],

    suggestedWallColor: "#F5F0EB",
    suggestedFloorColor: "#e8e4e0",
    suggestedFloorType: "tile",
  },
  {
    id: "studio-apartment",
    name: "Studio Apartment",
    icon: "🏢",
    dimensions: { width: 24, length: 18 },

    defaultFurniture: [
      {
        type: "queen-bed",
        name: "Queen Bed",
        x: 4,
        y: 0.5,
        width: 5,
        length: 6,
        color: "#dbd7d7",
      },
      {
        type: "l-shape-sofa",
        name: "L Shape Sofa",
        x: 14.6,
        y: 11.9,
        width: 9,
        length: 6,
        color: "#c6c2be",
        rotation: 180,
      },
      {
        type: "coffee-table",
        name: "Coffee Table",
        x: 15,
        y: 10.5,
        width: 4,
        length: 2,
        color: "#4682B4",
      },
      {
        type: "office-desk",
        name: "Office Desk",
        x: 18.5,
        y: 0.5,
        width: 5,
        length: 2.5,
        color: "#2F4F4F",
      },
      {
        type: "computer-chair",
        name: "Computer Chair",
        x: 20.5,
        y: 3.5,
        width: 2,
        length: 2,
        color: "#333333",
        rotation: 180,
      },
      {
        type: "tv-stand",
        name: "TV Stand",
        x: 8,
        y: 16,
        width: 6,
        length: 1.5,
        color: "#e69141",
        rotation: 180,
      },
      {
        type: "wardrobe-01",
        name: "Wardrobe",
        x: -1.3,
        y: 12,
        width: 5,
        length: 2,
        color: "#c6c2be",
        rotation: 270,
      },
    ],

    suggestedWallColor: "#F5F0EB",
    suggestedFloorColor: "#c9b9a6",
    suggestedFloorType: "wood",
  },

  {
    id: "lounge-room",
    name: "Lounge Room",
    icon: "📺",
    dimensions: { width: 20, length: 16 },

    defaultFurniture: [
      {
        type: "l-shape-sofa",
        name: "L Shape Sofa",
        x: 0.2,
        y: 0.2,
        width: 9,
        length: 6,
        color: "#c6c2be",
      },
      {
        type: "coffee-table",
        name: "Coffee Table",
        x: 4.5,
        y: 5.5,
        width: 4,
        length: 2,
        color: "#4682B4",
      },
      {
        type: "tv-stand",
        name: "TV Stand",
        x: 7,
        y: 14.2,
        width: 6,
        length: 1.5,
        color: "#e69141",
        rotation: 180,
      },
      {
        type: "books-helf",
        name: "Shelf",
        x: 16.5,
        y: 14.8,
        width: 3,
        length: 1,
        color: "#8B4513",
        rotation: 180,
      },
      {
        type: "arm-chair",
        name: "Reading Chair",
        x: 17,
        y: 5,
        width: 2.5,
        length: 2.5,
        color: "#228B22",
        rotation: 90,
      },
      {
        type: "arm-chair",
        name: "Reading Chair",
        x: 17,
        y: 8,
        width: 2.5,
        length: 2.5,
        color: "#228B22",
        rotation: 90,
      },
    ],

    suggestedWallColor: "#E8D5C4",
    suggestedFloorColor: "#c9b9a6",
    suggestedFloorType: "wood",
  },
];
